name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        working-directory: ./countries
        run: npm ci
      
      - name: Build
        working-directory: ./countries
        run: npm run build -- --configuration=production --base-href=/world_map/
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: countries/dist/hello-world
          branch: gh-pages
